### ISSUE TITLE
Checkbox and required

### ISSUE THREAD

**Issue by JoostKiens** [kaliberjs/forms#13]
I try to make a form with a required checkbox, for example 'I agree with the terms of service'. See the reduced test case below:

```jsx
import { useBooleanFormField, useForm } from '@kaliber/forms'
import { required } from '@kaliber/forms/validation'

export function Form() {
  const { form: { fields }, submit } = useForm({
    initialValues: { tos: false },
    fields: { tos: required },
    onSubmit: x => { console.log(x) },
  })

  return (
    <form onSubmit={submit}>
      <FormCheckbox label='I agree with the Terms of Service' field={fields.tos} />
      <button type='submit'>Submit</button>
    </form>
  )
}
function FormCheckbox({ label, field }) {
  const { name, state, eventHandlers } = useBooleanFormField(field)
  const { showError, error, value } = state
  console.log(showError, error)
  return (
    <>
      <div>
        <label htmlFor={name}>{label}</label>
        <input id={name} type='checkbox' checked={value || false} {...{ name }} {...eventHandlers} />
      </div>
      {showError && <p>{error.id}</p>}
    </>
  )
}

```

However this will not work, because the [`required`](https://github.com/kaliberjs/forms/blob/master/src/validation.js#L2) validation function explicitly allows `false` as a value. Meaning that there will never be an `error`.

We could solve this by writing our own validation function:

```jsx
function needsToBeChecked(x) {
  return x !== true && { id: 'needsToBeChecked' }
}

export function Form() {
  const { form: { fields }, submit } = useForm({
    initialValues: { tos: false },
    fields: { tos: needsToBeChecked },
    onSubmit: x => { console.log(x) },
  })
 ...
```

Is this the correct way to deal with this?

**Comment by EECOLOR** [comment]
Short answer: yes, this is the correct way to deal with this.

---

So in theory you could not give it an initial value and then set it to `required`. The `required` validation means that you require the user to set a value.

The user could then check and uncheck the checkbox to move past the `required` validation. In your case you not just want the user to interact with the field, you also want the field to be true. So I think the the following would reflect this in most detail:

```js
fields: { tos: [required, checked] }
```

Where `checked` can look like this:
```js
function checked(x) { return !x && error('checked') }
```

You solution is slightly different because it will give an error if the value is not strictly `true` and does not require the user to interact with the field.
